# Generated by Django 4.1 on 2022-08-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='origin_password',
            field=models.CharField(default='default_password', max_length=128),
        ),
    ]
