# Generated by Django 4.1 on 2022-08-15 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
